### ISSUE TITLE
consider allowing method="POST"

### ISSUE THREAD

**Issue by ItaiAxelrad** [oliverroick/netlify-plugin-html-validate#7]
Please consider allowing the value 'POST' for the method attribute as Netlify uses this for forms (see error below).

error: Attribute "method" has invalid value "POST", attribute-allowed-values

**Comment by oliverroick** [comment]
Hi @ItaiAxelrad,

this is because Netlify specifies the method attribute uppercase POST but it should be lowercase. This plugin does not define any validation rules so there's nothing I can do.

But you can overwrite the accepted attribute values for the `method` attribute. 

1. Create file `.htmlvalidate.json` (if you haven't already), which specifies the configuration for html-validate
2. Place the following in the file:

```json
{
  "extends": [
    "html-validate:standard",
  ],
  "elements": [
    "html5",
    {
      "form": {
        "attributes": {
          "method": ["POST", "GET", "post", "get"]
        }
      }
    }
  ]
}
```

This uses html-validate's standard config and overwrites what attributes are allowed for `method`
